DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Admin BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS Posts;
CREATE TABLE Posts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    User INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Body TEXT NOT NULL,
    Date DATETIME NOT NULL DEFAULT NOW(),
    Views INT NOT NULL DEFAULT 0,
    Categories VARCHAR(255) NOT NULL,

    FOREIGN KEY (User) REFERENCES Users(ID)
);

DROP TABLE IF EXISTS Replies;
CREATE TABLE Replies (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Thread INT NOT NULL,
    User INT NOT NULL,
    Body TEXT NOT NULL,
    Date DATETIME NOT NULL DEFAULT NOW(),

    FOREIGN KEY (Thread) REFERENCES Posts(ID),
    FOREIGN KEY (User) REFERENCES Users(ID)
);

DROP TABLE IF EXISTS Reports;
CREATE TABLE Reports (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Post INT NOT NULL,
    User INT NOT NULL,
    Body VARCHAR(1000) NOT NULL,
    Date DATETIME NOT NULL DEFAULT NOW(),

    FOREIGN KEY (Post) REFERENCES Posts(ID),
    FOREIGN KEY (User) REFERENCES Users(ID)
);

DROP TABLE IF EXISTS Votes;
CREATE TABLE Votes (
    User INT NOT NULL,
    Post INT NOT NULL,

    PRIMARY KEY (User, Post),
    FOREIGN KEY (User) REFERENCES Users(ID),
    FOREIGN KEY (Post) REFERENCES Posts(ID)
);