DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS Posts;
CREATE TABLE Posts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    `User` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `Body` TEXT NOT NULL,
    `Date` DATETIME NOT NULL,

    FOREIGN KEY (`User`) REFERENCES Users(ID)
);